/* Generated By:JavaCC: Do not edit this line. ReadFragsTokenManager.java */
package Parse;
import java.util.HashMap;
import java.util.Vector;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;

/** Token Manager. */
public class ReadFragsTokenManager implements ReadFragsConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x3fffffffffffc000L) != 0L)
         {
            jjmatchedKind = 63;
            return 5;
         }
         if ((active0 & 0x2000L) != 0L)
            return 9;
         return -1;
      case 1:
         if ((active0 & 0x3f7fc0ffffffc000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 1;
            return 5;
         }
         if ((active0 & 0x803f0000000000L) != 0L)
            return 5;
         return -1;
      case 2:
         if ((active0 & 0x380c00f6efffc000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 2;
            return 5;
         }
         if ((active0 & 0x773c00910000000L) != 0L)
            return 5;
         return -1;
      case 3:
         if ((active0 & 0x380800508ffcc000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 3;
            return 5;
         }
         if ((active0 & 0x400a660030000L) != 0L)
            return 5;
         return -1;
      case 4:
         if ((active0 & 0x2800000005fc8000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 4;
            return 5;
         }
         if ((active0 & 0x100800508a004000L) != 0L)
            return 5;
         return -1;
      case 5:
         if ((active0 & 0x47c0000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 5;
            return 5;
         }
         if ((active0 & 0x2800000001808000L) != 0L)
            return 5;
         return -1;
      case 6:
         if ((active0 & 0x1c0000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 6;
            return 5;
         }
         if ((active0 & 0x4600000L) != 0L)
            return 5;
         return -1;
      case 7:
         if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 7;
            return 5;
         }
         if ((active0 & 0xc0000L) != 0L)
            return 5;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 34:
         return jjStartNfaWithStates_0(0, 13, 9);
      case 40:
         return jjStopAtPos(0, 7);
      case 41:
         return jjStopAtPos(0, 8);
      case 44:
         return jjStopAtPos(0, 11);
      case 46:
         return jjStopAtPos(0, 6);
      case 58:
         return jjStopAtPos(0, 12);
      case 60:
         return jjStopAtPos(0, 9);
      case 62:
         return jjStopAtPos(0, 10);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x40000000200000L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x3800000009800000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x10c0000000L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x20000000040000L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x12100000000L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 71:
         return jjMoveStringLiteralDfa1_0(0x280000000000L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x6000000L);
      case 74:
         return jjMoveStringLiteralDfa1_0(0x200000000L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x144000000000L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x18000410100000L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x28000000000L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x80000000000000L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x4000000080000L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x700000800000000L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 85:
         return jjMoveStringLiteralDfa1_0(0x3c00000000000L);
      case 97:
         return jjMoveStringLiteralDfa1_0(0xc000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x20000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0xc040000000L);
      case 69:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 41, 5);
         else if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 44, 5);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 45, 5);
         return jjMoveStringLiteralDfa2_0(active0, 0x830000000L);
      case 71:
         return jjMoveStringLiteralDfa2_0(active0, 0x3000000000000L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x3828000008000000L);
      case 74:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L);
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x104c00000000000L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000000L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x480000000L);
      case 81:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 40, 5);
         break;
      case 82:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 55, 5);
         return jjMoveStringLiteralDfa2_0(active0, 0x600000000000000L);
      case 83:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L);
      case 84:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 42, 5);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 43, 5);
         break;
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000200000000L);
      case 88:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x1850000L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x6000000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x420000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 58, 5);
         break;
      case 66:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L);
      case 68:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 54, 5);
         break;
      case 69:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 47, 5);
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 49, 5);
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L);
      case 70:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 76:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 52, 5);
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 56, 5);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 57, 5);
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      case 77:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(2, 28, 5);
         return jjMoveStringLiteralDfa3_0(active0, 0x8220000000L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000088000000L);
      case 80:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(2, 32, 5);
         break;
      case 81:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(2, 35, 5);
         break;
      case 82:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      case 84:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 46, 5);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 48, 5);
         return jjMoveStringLiteralDfa3_0(active0, 0x3800000000000000L);
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x4001000000000L);
      case 86:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 53, 5);
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x1800000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x420000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x250000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000000L);
      case 69:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(3, 34, 5);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 39, 5);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L);
      case 76:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 5);
         break;
      case 77:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000008000000L);
      case 80:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(3, 29, 5);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(3, 33, 5);
         return jjMoveStringLiteralDfa4_0(active0, 0x800000L);
      case 81:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 37, 5);
         break;
      case 83:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 50, 5);
         return jjMoveStringLiteralDfa4_0(active0, 0x81000000L);
      case 85:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000000L);
      case 88:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000000000L);
      case 97:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 16, 5);
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000L);
      case 100:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(3, 17, 5);
         break;
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 70:
         return jjMoveStringLiteralDfa5_0(active0, 0x1c0000L);
      case 76:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 38, 5);
         break;
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000000000L);
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000000000L);
      case 80:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 5);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 36, 5);
         break;
      case 82:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 60, 5);
         break;
      case 83:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 51, 5);
         break;
      case 84:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 31, 5);
         break;
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x4600000L);
      case 103:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 25, 5);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
      case 110:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 14, 5);
         break;
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 68:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 59, 5);
         break;
      case 82:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 61, 5);
         break;
      case 98:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(5, 24, 5);
         break;
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x600000L);
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      case 114:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 23, 5);
         return jjMoveStringLiteralDfa6_0(active0, 0x1c0000L);
      case 122:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 15, 5);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x1c0000L);
      case 101:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(6, 26, 5);
         break;
      case 115:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(6, 21, 5);
         else if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(6, 22, 5);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 103:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(7, 18, 5);
         else if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(7, 19, 5);
         break;
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(8, 20, 5);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 9;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 63)
                        kind = 63;
                     jjCheckNAdd(5);
                  }
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(7, 8);
                  else if (curChar == 45)
                     jjAddStates(0, 1);
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 62)
                        kind = 62;
                     jjCheckNAdd(2);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 62)
                        kind = 62;
                  }
                  break;
               case 9:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(7, 8);
                  else if (curChar == 34)
                  {
                     if (kind > 64)
                        kind = 64;
                  }
                  break;
               case 1:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 62)
                     kind = 62;
                  jjCheckNAdd(2);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 62)
                     kind = 62;
                  jjCheckNAdd(2);
                  break;
               case 3:
                  if (curChar == 48 && kind > 62)
                     kind = 62;
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(5);
                  break;
               case 5:
                  if ((0x3ff400000000000L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(5);
                  break;
               case 6:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               case 7:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               case 8:
                  if (curChar == 34 && kind > 64)
                     kind = 64;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 5:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(5);
                  break;
               case 9:
               case 7:
                  jjCheckNAddTwoStates(7, 8);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 9:
               case 7:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 9 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   1, 3, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, "\56", "\50", "\51", "\74", "\76", "\54", 
"\72", "\42", "\141\154\151\147\156", "\141\163\143\151\151\172", "\144\141\164\141", 
"\167\157\162\144", "\104\141\164\141\106\162\141\147", "\120\162\157\143\106\162\141\147", 
"\115\151\160\163\106\162\141\155\145", "\101\143\164\165\141\154\163", "\106\157\162\155\141\154\163", 
"\102\141\144\120\164\162", "\102\141\144\123\165\142", "\111\156\122\145\147", 
"\111\156\106\162\141\155\145", "\102\111\116\117\120", "\115\105\115", "\124\105\115\120", 
"\103\101\114\114", "\103\117\116\123\124", "\105\130\120", "\112\125\115\120", 
"\115\117\126\105", "\123\105\121", "\103\112\125\115\120", "\105\123\105\121", 
"\114\101\102\105\114", "\116\101\115\105", "\105\121", "\116\105", "\114\124", "\107\124", 
"\114\105", "\107\105", "\125\114\124", "\125\114\105", "\125\107\124", "\125\107\105", 
"\120\114\125\123", "\115\111\116\125\123", "\115\125\114", "\104\111\126", "\101\116\104", 
"\117\122", "\123\114\114", "\123\122\114", "\123\122\101", "\102\111\124\101\116\104", 
"\102\111\124\117\122", "\102\111\124\130\117\122", null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffffffc1L, 0x1L, 
};
static final long[] jjtoSkip = {
   0x3eL, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[9];
static private final int[] jjstateSet = new int[18];
static protected char curChar;
/** Constructor. */
public ReadFragsTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public ReadFragsTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 9; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
