/* Generated By:JavaCC: Do not edit this line. ReadTypes.java */
package Translate;
import java.util.LinkedList;
public class ReadTypes implements ReadTypesConstants {

           private static Symbol.SymbolTable<Types.CLASS> classEnv =
                                          new Symbol.SymbolTable<Types.CLASS>();
           private static Types.CLASS referToClass(String cname)
           {
                        Types.CLASS c = classEnv.get(cname);
                        if (c == null)
                        {
                                c = new Types.CLASS(cname);
                                c.instance = new Types.OBJECT(c);
                                classEnv.put(cname, c);
                        }
                        return c;
           }

/**************************************************
 * The MiniJava language grammar starts here      *
 **************************************************/

//Program(AbstractList<ClassDecl> classes)
  static final public Absyn.Program Program() throws ParseException {
    LinkedList<Absyn.ClassDecl> cl = new LinkedList<Absyn.ClassDecl>();
    jj_consume_token(42);
    jj_consume_token(6);
    jj_consume_token(56);
    jj_consume_token(6);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 19:
      case 47:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 19:
        ClassDecl(cl);
        break;
      case 47:
        ThreadDecl(cl);
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(7);
    jj_consume_token(7);
    jj_consume_token(0);
      {if (true) return new Absyn.Program(cl);}
    throw new Error("Missing return statement in function");
  }

//ClassDecl(String name, String parent, LinkedList<VarDecl> fields, LinkedList<MethodDecl> methods)
  static final public void ClassDecl(LinkedList<Absyn.ClassDecl> cl) throws ParseException {
        Token name = null, parent = null;
        String parentName;
        LinkedList<Absyn.VarDecl> vl = new LinkedList<Absyn.VarDecl>();
        LinkedList<Absyn.MethodDecl> ml = new LinkedList<Absyn.MethodDecl>();
        Absyn.ClassDecl cd;
        Types.CLASS type;
    jj_consume_token(19);
    jj_consume_token(6);
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 57:
      jj_consume_token(57);
      break;
    case ID:
      parent = jj_consume_token(ID);
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(56);
    jj_consume_token(6);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 50:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      VarDecl(vl);
    }
    jj_consume_token(7);
    jj_consume_token(56);
    jj_consume_token(6);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 33:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      MethodDecl(ml);
    }
    jj_consume_token(7);
    type = ClassDescriptor();
    jj_consume_token(7);
                if (null == parent) parentName = null;
                else parentName = parent.toString();
                cd = new Absyn.ClassDecl(name.toString(), parentName, vl, ml);
                cl.add(cd);
                cd.type = type;
  }

//ThreadDecl(String name, LinkedList<VarDecl> fields, LinkedList<MethodDecl> methods)
  static final public void ThreadDecl(LinkedList<Absyn.ClassDecl> cl) throws ParseException {
        Token name = null, parent = null;
        LinkedList<Absyn.VarDecl> vl = new LinkedList<Absyn.VarDecl>();
        LinkedList<Absyn.MethodDecl> ml = new LinkedList<Absyn.MethodDecl>();
        Absyn.ThreadDecl td;
        Types.CLASS type;
    jj_consume_token(47);
    jj_consume_token(6);
    name = jj_consume_token(ID);
    jj_consume_token(58);
    jj_consume_token(56);
    jj_consume_token(6);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 50:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_4;
      }
      VarDecl(vl);
    }
    jj_consume_token(7);
    jj_consume_token(56);
    jj_consume_token(6);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 33:
      case 51:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 33:
        MethodDecl(ml);
        break;
      case 51:
        VoidDecl(ml);
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(7);
    type = ClassDescriptor();
    jj_consume_token(7);
                td = new Absyn.ThreadDecl(name.toString(), vl, ml);
                cl.add(td);
                td.type = type;
  }

//MethodDecl(Type returnType, String name,
//		      LinkedList<Formal> params,
//		      LinkedList<VarDecl> locals,
//		      LinkedList<Stmt> stmts,
//		      Expr returnVal)
  static final public void MethodDecl(LinkedList<Absyn.MethodDecl> ml) throws ParseException {
        Absyn.Type type = null;
        Token name;
        Absyn.Formal  param = null;
        Absyn.Stmt    stmt  = null;
        Absyn.Expr    expr  = null;
        boolean sync = false;
        LinkedList<Absyn.Formal> params   = new LinkedList<Absyn.Formal>();
        LinkedList<Absyn.VarDecl> locals  = new LinkedList<Absyn.VarDecl>();
        LinkedList<Absyn.Stmt> stmts      = new LinkedList<Absyn.Stmt>();
        Absyn.MethodDecl md = null;
        Types.FUNCTION function;
    jj_consume_token(33);
    jj_consume_token(6);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 55:
      jj_consume_token(55);
      break;
    case 12:
    case 17:
    case 28:
    case 31:
      type = Type();
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 59:
      jj_consume_token(59);
                            sync = true;
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    name = jj_consume_token(ID);
    jj_consume_token(56);
    jj_consume_token(6);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 25:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_6;
      }
      param = Formal();
                                                     params.add(param);
    }
    jj_consume_token(7);
    jj_consume_token(56);
    jj_consume_token(6);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 50:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_7;
      }
      VarDecl(locals);
    }
    jj_consume_token(7);
    jj_consume_token(56);
    jj_consume_token(6);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 14:
      case 16:
      case 29:
      case 52:
      case 54:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_8;
      }
      stmt = Stmt();
                                                   stmts.add(stmt);
    }
    jj_consume_token(7);
    expr = Expr();
    function = FunctionDescriptor();
    jj_consume_token(7);
                md = new Absyn.MethodDecl(type, sync, name.toString(),
                                                                  params, locals, stmts, expr);
                ml.add(md);
                md.function = function;
                Types.RECORD r = function.formals;
                for (Absyn.Formal f : params)
                {
                        f.checktype = r.get(f.name).type;
                }
  }

//VoidDecl(String name,
//		      LinkedList<VarDecl> locals,
//		      LinkedList<Stmt> stmts)
  static final public void VoidDecl(LinkedList<Absyn.MethodDecl> ml) throws ParseException {
        Token name;
        Absyn.Stmt    stmt  = null;
        LinkedList<Absyn.Formal> params   = new LinkedList<Absyn.Formal>();
        LinkedList<Absyn.VarDecl> locals  = new LinkedList<Absyn.VarDecl>();
        LinkedList<Absyn.Stmt> stmts      = new LinkedList<Absyn.Stmt>();
        Types.FUNCTION function;
        Absyn.VoidDecl vd;
    jj_consume_token(51);
    jj_consume_token(6);
    name = jj_consume_token(ID);
    jj_consume_token(56);
    jj_consume_token(6);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 50:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_9;
      }
      VarDecl(locals);
    }
    jj_consume_token(7);
    jj_consume_token(56);
    jj_consume_token(6);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 14:
      case 16:
      case 29:
      case 52:
      case 54:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_10;
      }
      stmt = Stmt();
                                                   stmts.add(stmt);
    }
    jj_consume_token(7);
    function = FunctionDescriptor();
    jj_consume_token(7);
                vd = new Absyn.VoidDecl(name.toString(), locals, stmts);
                ml.add(vd);
                vd.function = function;
                Types.RECORD r = function.formals;
                for (Absyn.Formal f : params)
                {
                        f.checktype = r.get(f.name).type;
                }
  }

//Formal(Type type, String name)
  static final public Absyn.Formal Formal() throws ParseException {
        Absyn.Type type;
        Token name;
    jj_consume_token(25);
    jj_consume_token(6);
    type = Type();
    name = jj_consume_token(ID);
    jj_consume_token(7);
          {if (true) return new Absyn.Formal(type, name.image);}
    throw new Error("Missing return statement in function");
  }

//VarDecl(Type type, String name, Expr init)
  static final public void VarDecl(LinkedList<Absyn.VarDecl> vl) throws ParseException {
        Absyn.Type type;
        Token name;
        Absyn.Expr init = null;
        Types.Type checktype;
        Absyn.VarDecl vd;
    jj_consume_token(50);
    jj_consume_token(6);
    type = Type();
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 57:
      jj_consume_token(57);
      break;
    case 9:
    case 10:
    case 11:
    case 18:
    case 20:
    case 21:
    case 23:
    case 24:
    case 26:
    case 27:
    case 30:
    case 32:
    case 34:
    case 35:
    case 36:
    case 37:
    case 38:
    case 39:
    case 40:
    case 41:
    case 44:
    case 45:
    case 46:
    case 48:
    case 53:
      init = Expr();
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    checktype = TypeDescriptor();
    jj_consume_token(7);
                vd = new Absyn.VarDecl(type, name.image, init);
                vl.add(vd);
                vd.semantType = checktype;
  }

  static final public Absyn.Type Type() throws ParseException {
 Absyn.Type t;
    if (jj_2_1(2147483647)) {
      t = ArrayType();
    } else if (jj_2_2(2147483647)) {
      t = BooleanType();
    } else if (jj_2_3(2147483647)) {
      t = IntegerType();
    } else if (jj_2_4(2147483647)) {
      t = IdentifierType();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
        {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

// ArrayType(Type base)
  static final public Absyn.Type ArrayType() throws ParseException {
  Absyn.Type t;
    jj_consume_token(12);
    jj_consume_token(6);
    t = Type();
    jj_consume_token(7);
          {if (true) return new Absyn.ArrayType(t);}
    throw new Error("Missing return statement in function");
  }

// BooleanType() { }
  static final public Absyn.Type BooleanType() throws ParseException {
    jj_consume_token(17);
          {if (true) return new Absyn.BooleanType();}
    throw new Error("Missing return statement in function");
  }

// IntegerType() { }
  static final public Absyn.Type IntegerType() throws ParseException {
    jj_consume_token(31);
          {if (true) return new Absyn.IntegerType();}
    throw new Error("Missing return statement in function");
  }

// IdentifierType(String id)
  static final public Absyn.Type IdentifierType() throws ParseException {
  Token t;
    jj_consume_token(28);
    jj_consume_token(6);
    t = jj_consume_token(ID);
    jj_consume_token(7);
          {if (true) return new Absyn.IdentifierType(t.image);}
    throw new Error("Missing return statement in function");
  }

  static final public Absyn.Stmt Stmt() throws ParseException {
        Absyn.Stmt s;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 14:
      s = AssignStmt();
      break;
    case 16:
      s = BlockStmt();
      break;
    case 29:
      s = IfStmt();
      break;
    case 54:
      s = XinuCallStmt();
      break;
    case 52:
      s = WhileStmt();
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
     {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

//AssignStmt(AssignableExpr lhs, Expr rhs)
  static final public Absyn.Stmt AssignStmt() throws ParseException {
        Absyn.Expr lhs = null, rhs = null;
    jj_consume_token(14);
    jj_consume_token(6);
    lhs = Expr();
    rhs = Expr();
    jj_consume_token(7);
          {if (true) return new Absyn.AssignStmt((Absyn.AssignableExpr) lhs, rhs);}
    throw new Error("Missing return statement in function");
  }

//BlockStmt(LinkedList<Stmt> stmts)
  static final public Absyn.Stmt BlockStmt() throws ParseException {
        Absyn.Stmt stmt = null;
        LinkedList<Absyn.Stmt> stmts      = new LinkedList<Absyn.Stmt>();
    jj_consume_token(16);
    jj_consume_token(6);
    jj_consume_token(56);
    jj_consume_token(6);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 14:
      case 16:
      case 29:
      case 52:
      case 54:
        ;
        break;
      default:
        jj_la1[17] = jj_gen;
        break label_11;
      }
      stmt = Stmt();
                                          stmts.add(stmt);
    }
    jj_consume_token(7);
    jj_consume_token(7);
          {if (true) return new Absyn.BlockStmt(stmts);}
    throw new Error("Missing return statement in function");
  }

//IfStmt(Expr test, Stmt thenStm, Stmt elseStm)
  static final public Absyn.Stmt IfStmt() throws ParseException {
        Absyn.Expr test;
        Absyn.Stmt thenStm, elseStm = null;
    jj_consume_token(29);
    jj_consume_token(6);
    test = Expr();
    thenStm = Stmt();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 57:
      jj_consume_token(57);
                  elseStm = null;
      break;
    case 14:
    case 16:
    case 29:
    case 52:
    case 54:
      elseStm = Stmt();
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(7);
          {if (true) return new Absyn.IfStmt(test, thenStm, elseStm);}
    throw new Error("Missing return statement in function");
  }

//XinuCallStmt(list of Expr)
  static final public Absyn.Stmt XinuCallStmt() throws ParseException {
        Token name;
        Absyn.Expr arg;
        LinkedList<Absyn.Expr> args      = new LinkedList<Absyn.Expr>();
    jj_consume_token(54);
    jj_consume_token(6);
    name = jj_consume_token(ID);
    jj_consume_token(56);
    jj_consume_token(6);
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 9:
      case 10:
      case 11:
      case 18:
      case 20:
      case 21:
      case 23:
      case 24:
      case 26:
      case 27:
      case 30:
      case 32:
      case 34:
      case 35:
      case 36:
      case 37:
      case 38:
      case 39:
      case 40:
      case 41:
      case 44:
      case 45:
      case 46:
      case 48:
      case 53:
        ;
        break;
      default:
        jj_la1[19] = jj_gen;
        break label_12;
      }
      arg = Expr();
                                       args.add(arg);
    }
    jj_consume_token(7);
    jj_consume_token(7);
                        {if (true) return new Absyn.XinuCallStmt(name.image, args);}
    throw new Error("Missing return statement in function");
  }

//WhileStmt(Expr test, Stmt body)
  static final public Absyn.Stmt WhileStmt() throws ParseException {
        Absyn.Expr test;
        Absyn.Stmt body;
    jj_consume_token(52);
    jj_consume_token(6);
    test = Expr();
    body = Stmt();
    jj_consume_token(7);
          {if (true) return new Absyn.WhileStmt(test, body);}
    throw new Error("Missing return statement in function");
  }

  static final public Absyn.Expr Expr() throws ParseException {
        Absyn.Expr e;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 9:
      e = AddExpr();
      break;
    case 10:
      e = AndExpr();
      break;
    case 11:
      e = ArrayExpr();
      break;
    case 18:
      e = CallExpr();
      break;
    case 20:
      e = DivExpr();
      break;
    case 21:
      e = EqualExpr();
      break;
    case 23:
      e = FalseExpr();
      break;
    case 24:
      e = FieldExpr();
      break;
    case 26:
      e = GreaterExpr();
      break;
    case 27:
      e = IdentifierExpr();
      break;
    case 32:
      e = LesserExpr();
      break;
    case 34:
      e = MulExpr();
      break;
    case 35:
      e = NegExpr();
      break;
    case 36:
      e = NewArrayExpr();
      break;
    case 37:
      e = NewObjectExpr();
      break;
    case 38:
      e = NotEqExpr();
      break;
    case 39:
      e = NotExpr();
      break;
    case 40:
      e = NullExpr();
      break;
    case 41:
      e = OrExpr();
      break;
    case 45:
      e = SubExpr();
      break;
    case 46:
      e = ThisExpr();
      break;
    case 48:
      e = TrueExpr();
      break;
    case 30:
      e = IntegerLiteral();
      break;
    case 44:
      e = StringLiteral();
      break;
    case 53:
      e = XinuCallExpr();
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

//AddExpr(Expr e1, Expr e2)
  static final public Absyn.AddExpr AddExpr() throws ParseException {
        Absyn.Expr e1, e2;
    jj_consume_token(9);
    jj_consume_token(6);
    e1 = Expr();
    e2 = Expr();
    jj_consume_token(7);
          {if (true) return new Absyn.AddExpr(e1, e2);}
    throw new Error("Missing return statement in function");
  }

//AndExpr(Expr e1, Expr e2)
  static final public Absyn.AndExpr AndExpr() throws ParseException {
        Absyn.Expr e1, e2;
    jj_consume_token(10);
    jj_consume_token(6);
    e1 = Expr();
    e2 = Expr();
    jj_consume_token(7);
          {if (true) return new Absyn.AndExpr(e1, e2);}
    throw new Error("Missing return statement in function");
  }

//DivExpr(Expr e1, Expr e2)
  static final public Absyn.DivExpr DivExpr() throws ParseException {
        Absyn.Expr e1, e2;
    jj_consume_token(20);
    jj_consume_token(6);
    e1 = Expr();
    e2 = Expr();
    jj_consume_token(7);
          {if (true) return new Absyn.DivExpr(e1, e2);}
    throw new Error("Missing return statement in function");
  }

//EqualExpr(Expr e1, Expr e2)
  static final public Absyn.EqualExpr EqualExpr() throws ParseException {
        Absyn.Expr e1, e2;
    jj_consume_token(21);
    jj_consume_token(6);
    e1 = Expr();
    e2 = Expr();
    jj_consume_token(7);
          {if (true) return new Absyn.EqualExpr(e1, e2);}
    throw new Error("Missing return statement in function");
  }

//GreaterExpr(Expr e1, Expr e2)
  static final public Absyn.GreaterExpr GreaterExpr() throws ParseException {
        Absyn.Expr e1, e2;
    jj_consume_token(26);
    jj_consume_token(6);
    e1 = Expr();
    e2 = Expr();
    jj_consume_token(7);
          {if (true) return new Absyn.GreaterExpr(e1, e2);}
    throw new Error("Missing return statement in function");
  }

//LesserExpr(Expr e1, Expr e2)
  static final public Absyn.LesserExpr LesserExpr() throws ParseException {
        Absyn.Expr e1, e2;
    jj_consume_token(32);
    jj_consume_token(6);
    e1 = Expr();
    e2 = Expr();
    jj_consume_token(7);
          {if (true) return new Absyn.LesserExpr(e1, e2);}
    throw new Error("Missing return statement in function");
  }

//MulExpr(Expr e1, Expr e2)
  static final public Absyn.MulExpr MulExpr() throws ParseException {
        Absyn.Expr e1, e2;
    jj_consume_token(34);
    jj_consume_token(6);
    e1 = Expr();
    e2 = Expr();
    jj_consume_token(7);
          {if (true) return new Absyn.MulExpr(e1, e2);}
    throw new Error("Missing return statement in function");
  }

//NotEqExpr(Expr e1, Expr e2)
  static final public Absyn.NotEqExpr NotEqExpr() throws ParseException {
        Absyn.Expr e1, e2;
    jj_consume_token(38);
    jj_consume_token(6);
    e1 = Expr();
    e2 = Expr();
    jj_consume_token(7);
          {if (true) return new Absyn.NotEqExpr(e1, e2);}
    throw new Error("Missing return statement in function");
  }

//OrExpr(Expr e1, Expr e2)
  static final public Absyn.OrExpr OrExpr() throws ParseException {
        Absyn.Expr e1, e2;
    jj_consume_token(41);
    jj_consume_token(6);
    e1 = Expr();
    e2 = Expr();
    jj_consume_token(7);
          {if (true) return new Absyn.OrExpr(e1, e2);}
    throw new Error("Missing return statement in function");
  }

//SubExpr(Expr e1, Expr e2)
  static final public Absyn.SubExpr SubExpr() throws ParseException {
        Absyn.Expr e1, e2;
    jj_consume_token(45);
    jj_consume_token(6);
    e1 = Expr();
    e2 = Expr();
    jj_consume_token(7);
          {if (true) return new Absyn.SubExpr(e1, e2);}
    throw new Error("Missing return statement in function");
  }

//ArrayExpr(Expr target, Expr index)
  static final public Absyn.ArrayExpr ArrayExpr() throws ParseException {
        Absyn.Expr target, index;
    jj_consume_token(11);
    jj_consume_token(6);
    target = Expr();
    index = Expr();
    jj_consume_token(7);
          {if (true) return new Absyn.ArrayExpr(target, index);}
    throw new Error("Missing return statement in function");
  }

//CallExpr(Expr target, String method, LinkedList<Expr> args)
  static final public Absyn.CallExpr CallExpr() throws ParseException {
        Absyn.Expr target;
        Token method;
        Absyn.Expr arg;
        LinkedList<Absyn.Expr> args = new LinkedList<Absyn.Expr>();
        Token index;
    jj_consume_token(18);
    jj_consume_token(6);
    target = Expr();
    method = jj_consume_token(ID);
    jj_consume_token(56);
    jj_consume_token(6);
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 9:
      case 10:
      case 11:
      case 18:
      case 20:
      case 21:
      case 23:
      case 24:
      case 26:
      case 27:
      case 30:
      case 32:
      case 34:
      case 35:
      case 36:
      case 37:
      case 38:
      case 39:
      case 40:
      case 41:
      case 44:
      case 45:
      case 46:
      case 48:
      case 53:
        ;
        break;
      default:
        jj_la1[21] = jj_gen;
        break label_13;
      }
      arg = Expr();
                                       args.add(arg);
    }
    jj_consume_token(7);
    index = jj_consume_token(INT);
    jj_consume_token(7);
          Absyn.CallExpr ce = new Absyn.CallExpr(target, method.image, args);
          ce.id = new Integer(index.toString());
          {if (true) return ce;}
    throw new Error("Missing return statement in function");
  }

//FalseExpr()
  static final public Absyn.FalseExpr FalseExpr() throws ParseException {
    jj_consume_token(23);
          {if (true) return new Absyn.FalseExpr();}
    throw new Error("Missing return statement in function");
  }

//FieldExpr(Expr target, String field)
  static final public Absyn.FieldExpr FieldExpr() throws ParseException {
        Absyn.Expr target;
        Token field;
        Token index;
    jj_consume_token(24);
    jj_consume_token(6);
    target = Expr();
    field = jj_consume_token(ID);
    index = jj_consume_token(INT);
    jj_consume_token(7);
                Absyn.FieldExpr fe = new Absyn.FieldExpr(target, field.image);
                fe.id = new Integer(index.toString());
                {if (true) return fe;}
    throw new Error("Missing return statement in function");
  }

//IdentifierExpr(String id)
  static final public Absyn.IdentifierExpr IdentifierExpr() throws ParseException {
        Token id;
    jj_consume_token(27);
    jj_consume_token(6);
    id = jj_consume_token(ID);
    jj_consume_token(7);
          {if (true) return new Absyn.IdentifierExpr(id.image);}
    throw new Error("Missing return statement in function");
  }

//NegExpr(Expr e1)
  static final public Absyn.NegExpr NegExpr() throws ParseException {
        Absyn.Expr e1;
    jj_consume_token(35);
    jj_consume_token(6);
    e1 = Expr();
    jj_consume_token(7);
         {if (true) return new Absyn.NegExpr(e1);}
    throw new Error("Missing return statement in function");
  }

//NewArrayExpr(Type type, LinkedList<Expr> dimensions)
  static final public Absyn.NewArrayExpr NewArrayExpr() throws ParseException {
        Absyn.Type type;
        Absyn.Expr expr;
        LinkedList<Absyn.Expr> dimensions = new LinkedList<Absyn.Expr>();
    jj_consume_token(36);
    jj_consume_token(6);
    type = Type();
    jj_consume_token(56);
    jj_consume_token(6);
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 9:
      case 10:
      case 11:
      case 18:
      case 20:
      case 21:
      case 23:
      case 24:
      case 26:
      case 27:
      case 30:
      case 32:
      case 34:
      case 35:
      case 36:
      case 37:
      case 38:
      case 39:
      case 40:
      case 41:
      case 44:
      case 45:
      case 46:
      case 48:
      case 53:
      case 57:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_14;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 9:
      case 10:
      case 11:
      case 18:
      case 20:
      case 21:
      case 23:
      case 24:
      case 26:
      case 27:
      case 30:
      case 32:
      case 34:
      case 35:
      case 36:
      case 37:
      case 38:
      case 39:
      case 40:
      case 41:
      case 44:
      case 45:
      case 46:
      case 48:
      case 53:
        expr = Expr();
                                         dimensions.add(expr);
        break;
      case 57:
        jj_consume_token(57);
                                  dimensions.add(null);
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(7);
    jj_consume_token(7);
          {if (true) return new Absyn.NewArrayExpr(type, dimensions);}
    throw new Error("Missing return statement in function");
  }

//NewObjectExpr(Type type)
  static final public Absyn.NewObjectExpr NewObjectExpr() throws ParseException {
        Absyn.Type type;
    jj_consume_token(37);
    jj_consume_token(6);
    type = Type();
    jj_consume_token(7);
          {if (true) return new Absyn.NewObjectExpr(type);}
    throw new Error("Missing return statement in function");
  }

//NotExpr(Expr e1)
  static final public Absyn.NotExpr NotExpr() throws ParseException {
        Absyn.Expr e1;
    jj_consume_token(39);
    jj_consume_token(6);
    e1 = Expr();
    jj_consume_token(7);
          {if (true) return new Absyn.NotExpr(e1);}
    throw new Error("Missing return statement in function");
  }

//NullExpr()
  static final public Absyn.NullExpr NullExpr() throws ParseException {
    jj_consume_token(40);
          {if (true) return new Absyn.NullExpr();}
    throw new Error("Missing return statement in function");
  }

//XinuCallExpr(list of Expr)
  static final public Absyn.XinuCallExpr XinuCallExpr() throws ParseException {
        Token name;
        Absyn.Expr arg;
        LinkedList<Absyn.Expr> args      = new LinkedList<Absyn.Expr>();
    jj_consume_token(53);
    jj_consume_token(6);
    name = jj_consume_token(ID);
    jj_consume_token(56);
    jj_consume_token(6);
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 9:
      case 10:
      case 11:
      case 18:
      case 20:
      case 21:
      case 23:
      case 24:
      case 26:
      case 27:
      case 30:
      case 32:
      case 34:
      case 35:
      case 36:
      case 37:
      case 38:
      case 39:
      case 40:
      case 41:
      case 44:
      case 45:
      case 46:
      case 48:
      case 53:
        ;
        break;
      default:
        jj_la1[24] = jj_gen;
        break label_15;
      }
      arg = Expr();
                                       args.add(arg);
    }
    jj_consume_token(7);
    jj_consume_token(7);
                        {if (true) return new Absyn.XinuCallExpr(name.image, args);}
    throw new Error("Missing return statement in function");
  }

//ThisExpr()
  static final public Absyn.ThisExpr ThisExpr() throws ParseException {
    jj_consume_token(46);
          {if (true) return new Absyn.ThisExpr();}
    throw new Error("Missing return statement in function");
  }

//TrueExpr()
  static final public Absyn.TrueExpr TrueExpr() throws ParseException {
    jj_consume_token(48);
          {if (true) return new Absyn.TrueExpr();}
    throw new Error("Missing return statement in function");
  }

//IntegerLiteral(int value)
  static final public Absyn.IntegerLiteral IntegerLiteral() throws ParseException {
  Token t;
    jj_consume_token(30);
    jj_consume_token(6);
    t = jj_consume_token(INT);
    jj_consume_token(7);
          {if (true) return new Absyn.IntegerLiteral(new Integer(t.toString()));}
    throw new Error("Missing return statement in function");
  }

//StringLiteral(String value)
  static final public Absyn.StringLiteral StringLiteral() throws ParseException {
  Token t;
    jj_consume_token(44);
    jj_consume_token(6);
    t = jj_consume_token(STRING);
    jj_consume_token(7);
          {if (true) return new Absyn.StringLiteral(t.toString());}
    throw new Error("Missing return statement in function");
  }

  static final public Types.Type TypeDescriptor() throws ParseException {
        Types.Type t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 60:
      t = ArrayDescriptor();
      break;
    case 62:
      t = ClassDescriptor();
      break;
    case 63:
      t = FieldDescriptor();
      break;
    case 64:
      t = FunctionDescriptor();
      break;
    case 67:
      t = ObjectDescriptor();
      break;
    case 68:
      t = RecordDescriptor();
      break;
    case 61:
      jj_consume_token(61);
                      {if (true) return new Types.BOOLEAN();}
      break;
    case 65:
      jj_consume_token(65);
                      {if (true) return new Types.INT();}
      break;
    case 66:
      jj_consume_token(66);
                      {if (true) return new Types.NIL();}
      break;
    case 69:
      jj_consume_token(69);
                      {if (true) return new Types.STRING();}
      break;
    case 70:
      jj_consume_token(70);
                      {if (true) return new Types.VOID();}
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  static final public Types.ARRAY ArrayDescriptor() throws ParseException {
        Types.Type t;
    jj_consume_token(60);
    jj_consume_token(6);
    t = TypeDescriptor();
    jj_consume_token(7);
          {if (true) return new Types.ARRAY(t);}
    throw new Error("Missing return statement in function");
  }

  static final public Types.CLASS ClassDescriptor() throws ParseException {
        Token cname = null, pname = null, oname = null;
        Types.RECORD methods, fields, imethods, ifields;
        Types.OBJECT instance;
        Types.CLASS c;
    jj_consume_token(62);
    jj_consume_token(6);
    cname = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 57:
      jj_consume_token(57);
      break;
    case 58:
      pname = jj_consume_token(58);
      break;
    case ID:
      pname = jj_consume_token(ID);
      break;
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    methods = RecordDescriptor();
    fields = RecordDescriptor();
    jj_consume_token(67);
    jj_consume_token(6);
    oname = jj_consume_token(ID);
    imethods = RecordDescriptor();
    ifields = RecordDescriptor();
    jj_consume_token(7);
    jj_consume_token(7);
                c = referToClass(cname.toString());
                if (pname != null)
                { c.parent = referToClass(pname.toString()); }
                c.methods  = methods;
                c.fields   = fields;
                c.instance.methods = imethods;
                c.instance.fields  = ifields;
                {if (true) return c;}
    throw new Error("Missing return statement in function");
  }

  static final public Types.FIELD FieldDescriptor() throws ParseException {
        Token index = null, fname = null;
        Types.Type t;
    jj_consume_token(63);
    jj_consume_token(6);
    index = jj_consume_token(INT);
    fname = jj_consume_token(ID);
    t = TypeDescriptor();
    jj_consume_token(7);
                {if (true) return new Types.FIELD(t, fname.toString(),
                                                                  new Integer(index.toString()));}
    throw new Error("Missing return statement in function");
  }

  static final public Types.FUNCTION FunctionDescriptor() throws ParseException {
        Token name = null;
        Types.Type self = null, result = null;
        Types.RECORD formals = null;
    jj_consume_token(64);
    jj_consume_token(6);
    name = jj_consume_token(ID);
    self = TypeDescriptor();
    formals = RecordDescriptor();
    result = TypeDescriptor();
    jj_consume_token(7);
                {if (true) return new Types.FUNCTION(name.toString(), (Types.OBJECT)self, formals, result);}
    throw new Error("Missing return statement in function");
  }

  static final public Types.OBJECT ObjectDescriptor() throws ParseException {
        Token name;
    jj_consume_token(67);
    jj_consume_token(6);
    name = jj_consume_token(ID);
    jj_consume_token(7);
          {if (true) return referToClass(name.toString()).instance;}
    throw new Error("Missing return statement in function");
  }

  static final public Types.RECORD RecordDescriptor() throws ParseException {
        Types.RECORD r = new Types.RECORD();
        Types.FIELD  f = null;
    jj_consume_token(68);
    jj_consume_token(6);
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 63:
        ;
        break;
      default:
        jj_la1[27] = jj_gen;
        break label_16;
      }
      f = FieldDescriptor();
                                  r.put(f.type, f.name);
    }
    jj_consume_token(7);
          {if (true) return r;}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_3R_25() {
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_scan_token(17)) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3R_22() {
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3R_21() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_scan_token(28)) return true;
    if (jj_scan_token(6)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(7)) return true;
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_scan_token(12)) return true;
    if (jj_scan_token(6)) return true;
    if (jj_3R_21()) return true;
    if (jj_scan_token(7)) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_scan_token(31)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public ReadTypesTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[28];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x80000,0x80000,0x0,0x0,0x0,0x0,0x0,0x0,0x90021000,0x0,0x2000000,0x0,0x20014000,0x0,0x20014000,0x4db40e00,0x20014000,0x20014000,0x20014000,0x4db40e00,0x4db40e00,0x4db40e00,0x4db40e00,0x4db40e00,0x4db40e00,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x8000,0x8000,0x2000000,0x40000,0x2,0x40000,0x80002,0x80002,0x800000,0x8000000,0x0,0x40000,0x500000,0x40000,0x500000,0x22173fd,0x500000,0x500000,0x2500000,0x2173fd,0x2173fd,0x2173fd,0x22173fd,0x22173fd,0x2173fd,0xf0000000,0x6000000,0x80000000,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x40000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x7f,0x40000,0x0,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[4];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public ReadTypes(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public ReadTypes(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ReadTypesTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 28; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 28; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public ReadTypes(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ReadTypesTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 28; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 28; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public ReadTypes(ReadTypesTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 28; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ReadTypesTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 28; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List jj_expentries = new java.util.ArrayList();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[86];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 28; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 86; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 4; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
