/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package Parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 51;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 52;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 53;
  /** RegularExpression Id. */
  int INT = 55;
  /** RegularExpression Id. */
  int OCT = 56;
  /** RegularExpression Id. */
  int HEX = 57;
  /** RegularExpression Id. */
  int STRING = 58;
  /** RegularExpression Id. */
  int ID = 59;
  /** RegularExpression Id. */
  int LETTER = 60;
  /** RegularExpression Id. */
  int DIGIT = 61;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"-\"",
    "\"!\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\",\"",
    "\";\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"String\"",
    "\"class\"",
    "\"extends\"",
    "\"Thread\"",
    "\"synchronized\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"Xinu\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"null\"",
    "\"new\"",
    "\"int\"",
    "\"boolean\"",
    "\"//\"",
    "<token of kind 49>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 54>",
    "<INT>",
    "<OCT>",
    "<HEX>",
    "<STRING>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "<token of kind 62>",
  };

}
