package frontend.parse;

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 * NOTE: This interface is LEGACY and a product of the original JavaCC generation of this parser code.
 * As of 2017-07-26, it has been pruned of unused code.
 * Feel free to remove or refactor it if it no longer satisfies requirements.
 */
public interface MiniJavaParserConstants {
    /** RegularExpression Id. */
    int INT = 55;
    /** RegularExpression Id. */
    int STRING = 58;
    /** RegularExpression Id. */
    int ID = 59;
}
